### ISSUE TITLE
Questions in notebook 2016-10-19-implicit-mf-part-1.ipynb

### ISSUE THREAD

**Issue by foreveryang0208** [EthanRosenthal/DataPiques_source#1]
Hi Ethan,

First of all thank you very much for your posts and notebooks. I rarely come across such detailed rich python recommender tutorials online like yours. 

I've been trying to replicate the process in the notebook 2016-10-19-implicit-mf-part-1.ipynb. I can follow pretty much all the contents, except I get stuck at the functions calculate_mse, and precision_at_k. Perhaps when you implemented them, the implicit library had an order version, but now the model.predict_for_customers() does not exist anymore. May I ask what would be a remedy for this? I've thought about using model.recommend() instead, but I'm not too sure how to adjust the training matrix or testing matrix accordingly.

Secondly I discovered that the model.fit() method expects the rating matrix to have items as rows, users as columns. Yet you seem to shape the rating matrix as users as rows, items as columns. Do you think this would be a problem?

Hope to hear from you.

Many thanks

**Comment by EthanRosenthal** [comment]
Hi,

You're correct that I was using a previous version of `implicit`. And in fact, I am actually using my own [fork](https://github.com/EthanRosenthal/implicit) of the library. At the time when I wrote the blog post, the library was pure functions, so I wanted to add a simple object interface for running grid searches. `implicit` has changed quite a bit since then. 

The fork should still work for replicating the results. One day, maybe I'll update the post for the more recent version of implicit...

And in terms of your last question regarding user rows vs item rows, I believe that this would be an issue for the new version of implicit but should not matter with my fork.

Good luck!
Ethan
